version: '2'
services:
    trainingapp-app:
        image: trainingapp
        external_links:
            - trainingapp-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/TrainingApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trainingapp-postgresql:
        extends:
            file: postgresql.yml
            service: trainingapp-postgresql
